services:
  mysql:
    image: mysql:8
    container_name: kitchentech-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: kitchentech
      JWT_SECURITY_KEY: ${JWT_SECURITY_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECURITY_KEY: 586E3272357538782F413F4428472B4B6250655368566B597033733676397924
      JWT_EXPIRATION: 86400000
      JWT_REFRESH_EXPIRATION: 604800000

volumes:
  mysql_data:
